"""Evaluate the detector on the held-out test set and publish the numbers.

    python -m ml.evaluate --weights ml/runs/hazards/weights/best.pt --data ml/data/prepared/data.yaml

We publish per-class mAP@50, a confusion matrix, and precision/recall curves — including for the
classes that do badly. A single headline mAP hides exactly what a judge would find by pointing the
app at their own house, and the honest framing is a selling point rather than a liability (risk R1).

The test split is touched here and nowhere else. Tuning against it would turn our published metrics
into training scores.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from ml.dataset import load_taxonomy

# Below this, a class is not good enough to state as a finding. It can still ship, but the app
# should treat it as "possible — confirm" rather than as a detection.
USABLE_MAP50 = 0.50


def evaluate(weights: Path, data: Path, out_dir: Path, *, split: str = "test") -> dict:
    from ultralytics import YOLO

    model = YOLO(str(weights))
    metrics = model.val(data=str(data), split=split, plots=True)

    classes = load_taxonomy()
    names = {c["index"]: c["name"] for c in classes}

    per_class = {}
    for position, class_index in enumerate(metrics.ap_class_index):
        per_class[names[int(class_index)]] = {
            "map50": float(metrics.box.ap50[position]),
            "map50_95": float(metrics.box.ap[position]),
            "precision": float(metrics.box.p[position]),
            "recall": float(metrics.box.r[position]),
        }

    report = {
        "split": split,
        "weights": str(weights),
        "overall": {
            "map50": float(metrics.box.map50),
            "map50_95": float(metrics.box.map),
            "precision": float(metrics.box.mp),
            "recall": float(metrics.box.mr),
        },
        "per_class": per_class,
        "below_usable_bar": sorted(
            name for name, m in per_class.items() if m["map50"] < USABLE_MAP50
        ),
        "usable_bar_map50": USABLE_MAP50,
        "plots_dir": str(metrics.save_dir),
    }

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "metrics.json").write_text(json.dumps(report, indent=2) + "\n")
    (out_dir / "METRICS.md").write_text(render_markdown(report))
    return report


def render_markdown(report: dict) -> str:
    """A table we can paste into the repository and cite in the written answers."""
    lines = [
        "# Detector metrics",
        "",
        f"Held-out **{report['split']}** split. Split by property, so no house in this set appears",
        "in training. Generated by `ml/evaluate.py`; do not edit by hand.",
        "",
        f"**Overall mAP@50: {report['overall']['map50']:.3f}** "
        f"(mAP@50-95 {report['overall']['map50_95']:.3f}, "
        f"precision {report['overall']['precision']:.3f}, "
        f"recall {report['overall']['recall']:.3f})",
        "",
        "| Class | mAP@50 | mAP@50-95 | Precision | Recall |",
        "|---|---:|---:|---:|---:|",
    ]
    for name, metrics in sorted(report["per_class"].items()):
        lines.append(
            f"| `{name}` | {metrics['map50']:.3f} | {metrics['map50_95']:.3f} | "
            f"{metrics['precision']:.3f} | {metrics['recall']:.3f} |"
        )

    lines += ["", "## Classes below the usable bar", ""]
    if report["below_usable_bar"]:
        lines.append(
            f"These scored under mAP@50 {report['usable_bar_map50']:.2f} and are surfaced in the "
            "app as *possible — confirm* rather than as detections:"
        )
        lines += [f"- `{name}`" for name in report["below_usable_bar"]]
    else:
        lines.append("None — every class cleared the bar.")

    lines += [
        "",
        "## How to read this",
        "",
        "Detections are advisory. The rules engine scores a property from confirmed findings and",
        "the user's own checklist answers, so a missed hazard does not silently produce a clean",
        "plan — the checklist still asks. Confusion matrix and precision/recall curves are in",
        f"`{report['plots_dir']}`.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--weights", required=True, type=Path)
    parser.add_argument("--data", required=True, type=Path)
    parser.add_argument("--out", type=Path, default=Path("ml/metrics"))
    parser.add_argument("--split", default="test", choices=["test", "val"])
    args = parser.parse_args()

    report = evaluate(args.weights, args.data, args.out, split=args.split)
    print(json.dumps(report["overall"], indent=2))
    if report["below_usable_bar"]:
        print("\nbelow the usable bar:", ", ".join(report["below_usable_bar"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
